import type { Metadata } from "next";
import Head from 'next/head';
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Facebook advertising support",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <Head>
        <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta name="DC.title" content="Facebook advertising support" />
        <meta name="revisit-after" content="1 day" />
        <meta name="description" content="Facebook advertising support" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="distribution" content="GLOBAL" />
        <meta name="rating" content="General" />
        <meta name="copyright" content="Copyright - 2022 META" />
        <meta name="author" content="META" />
        <meta name="theme-color" content="#FFF" />
        <meta name="robots" content="noindex,nofollow" />
      </Head>
      <body>
      <main>{children}</main>

      </body>
    </html>
  );
}
